set encoding=utf-8

syntax on
set number
set list
set list listchars=tab:»-,trail:_,extends:»,precedes:«,nbsp:%

autocmd VimEnter,Colorscheme * highlight SpecialKey cterm=NONE ctermfg=243 ctermbg=NONE
"全角スペースをハイライト表示
function! ZenkakuSpace()
    highlight ZenkakuSpace cterm=reverse ctermfg=6 gui=reverse guifg=DarkMagenta
endfunction

if has('syntax')
	augroup ZenkakuSpace
		autocmd!
		autocmd ColorScheme       * call ZenkakuSpace()
		autocmd VimEnter,WinEnter * match ZenkakuSpace /　/
	augroup END
	call ZenkakuSpace()
endif

set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4

set backspace=2
set nobackup
set whichwrap=b,s,h,l,<,>,[,]
set clipboard=unnamed,autoselect
set noundofile

map <C-l> gt
map <C-h> gT
